const REQUIREMENT_STATUS = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  CLOSED: 'CLOSED',
  AWARDED: 'AWARDED',
};

const PARTICIPANT_STATUS = {
  INVITED: 'INVITED',
  JOINED: 'JOINED',
};

module.exports = { REQUIREMENT_STATUS, PARTICIPANT_STATUS };
